# Site settings
title: sonniesedge
email: charlie@sonniesedge.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Sonniesedge writes things for love and profit.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sonniesedge.co.uk" # the base hostname & protocol for your site
twitter_username: sonniesedge
github_username:  sonniesedge

# Build settings
markdown: kramdown


source: source
destination: _build

small: 320px
medium: 500px
large: 1120px

permalink: /blog/:title